# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convertGui.ui'
#
# Created: Sat Feb  8 16:37:20 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(366, 380)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 270000))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 321, 62))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.txtDcm = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDcm.sizePolicy().hasHeightForWidth())
        self.txtDcm.setSizePolicy(sizePolicy)
        self.txtDcm.setObjectName(_fromUtf8("txtDcm"))
        self.horizontalLayout_2.addWidget(self.txtDcm)
        self.cmdDcm = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdDcm.sizePolicy().hasHeightForWidth())
        self.cmdDcm.setSizePolicy(sizePolicy)
        self.cmdDcm.setMinimumSize(QtCore.QSize(31, 27))
        self.cmdDcm.setMaximumSize(QtCore.QSize(31, 27))
        self.cmdDcm.setObjectName(_fromUtf8("cmdDcm"))
        self.horizontalLayout_2.addWidget(self.cmdDcm)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.cmdStartConvert = QtGui.QPushButton(self.tab)
        self.cmdStartConvert.setGeometry(QtCore.QRect(10, 230, 85, 31))
        self.cmdStartConvert.setObjectName(_fromUtf8("cmdStartConvert"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(9, 9, 321, 62))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.txtProject = QtGui.QLineEdit(self.layoutWidget1)
        self.txtProject.setObjectName(_fromUtf8("txtProject"))
        self.horizontalLayout.addWidget(self.txtProject)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.cmdStartToSave = QtGui.QPushButton(self.tab_2)
        self.cmdStartToSave.setGeometry(QtCore.QRect(10, 230, 81, 31))
        self.cmdStartToSave.setObjectName(_fromUtf8("cmdStartToSave"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 100, 321, 60))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.nutMinGray = QtGui.QSpinBox(self.gridLayoutWidget)
        self.nutMinGray.setMaximum(65535)
        self.nutMinGray.setObjectName(_fromUtf8("nutMinGray"))
        self.gridLayout_2.addWidget(self.nutMinGray, 1, 1, 1, 1)
        self.sldMinGray = QtGui.QSlider(self.gridLayoutWidget)
        self.sldMinGray.setMaximum(65535)
        self.sldMinGray.setOrientation(QtCore.Qt.Horizontal)
        self.sldMinGray.setObjectName(_fromUtf8("sldMinGray"))
        self.gridLayout_2.addWidget(self.sldMinGray, 1, 0, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 160, 321, 60))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.nutMaxGray = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.nutMaxGray.setMaximum(65535)
        self.nutMaxGray.setProperty("value", 1000)
        self.nutMaxGray.setObjectName(_fromUtf8("nutMaxGray"))
        self.gridLayout_3.addWidget(self.nutMaxGray, 1, 1, 1, 1)
        self.sldMaxGray = QtGui.QSlider(self.gridLayoutWidget_2)
        self.sldMaxGray.setMaximum(65535)
        self.sldMaxGray.setOrientation(QtCore.Qt.Horizontal)
        self.sldMaxGray.setObjectName(_fromUtf8("sldMaxGray"))
        self.gridLayout_3.addWidget(self.sldMaxGray, 1, 0, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 70, 321, 28))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.chkFlipTop = QtGui.QCheckBox(self.layoutWidget2)
        self.chkFlipTop.setObjectName(_fromUtf8("chkFlipTop"))
        self.horizontalLayout_3.addWidget(self.chkFlipTop)
        self.chkFlipRight = QtGui.QCheckBox(self.layoutWidget2)
        self.chkFlipRight.setObjectName(_fromUtf8("chkFlipRight"))
        self.horizontalLayout_3.addWidget(self.chkFlipRight)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.cmdStartEditor = QtGui.QPushButton(self.tab_3)
        self.cmdStartEditor.setGeometry(QtCore.QRect(10, 230, 85, 31))
        self.cmdStartEditor.setObjectName(_fromUtf8("cmdStartEditor"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 321, 61))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.cmbProjects = QtGui.QComboBox(self.verticalLayoutWidget)
        self.cmbProjects.setObjectName(_fromUtf8("cmbProjects"))
        self.verticalLayout_3.addWidget(self.cmbProjects)
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 325, 33))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.chkRemoveVoluminas = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkRemoveVoluminas.setObjectName(_fromUtf8("chkRemoveVoluminas"))
        self.horizontalLayout_4.addWidget(self.chkRemoveVoluminas)
        self.nutRemoveVoluminas = QtGui.QSpinBox(self.horizontalLayoutWidget)
        self.nutRemoveVoluminas.setMaximum(65535)
        self.nutRemoveVoluminas.setObjectName(_fromUtf8("nutRemoveVoluminas"))
        self.horizontalLayout_4.addWidget(self.nutRemoveVoluminas)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.tab_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 120, 325, 33))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.chkFillCavities = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.chkFillCavities.setObjectName(_fromUtf8("chkFillCavities"))
        self.horizontalLayout_6.addWidget(self.chkFillCavities)
        self.nutFillCavities = QtGui.QSpinBox(self.horizontalLayoutWidget_3)
        self.nutFillCavities.setMaximum(65535)
        self.nutFillCavities.setObjectName(_fromUtf8("nutFillCavities"))
        self.horizontalLayout_6.addWidget(self.nutFillCavities)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 366, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txtDcm, self.cmdDcm)
        MainWindow.setTabOrder(self.cmdDcm, self.cmdStartConvert)
        MainWindow.setTabOrder(self.cmdStartConvert, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.txtProject)
        MainWindow.setTabOrder(self.txtProject, self.chkFlipTop)
        MainWindow.setTabOrder(self.chkFlipTop, self.chkFlipRight)
        MainWindow.setTabOrder(self.chkFlipRight, self.sldMinGray)
        MainWindow.setTabOrder(self.sldMinGray, self.nutMinGray)
        MainWindow.setTabOrder(self.nutMinGray, self.sldMaxGray)
        MainWindow.setTabOrder(self.sldMaxGray, self.nutMaxGray)
        MainWindow.setTabOrder(self.nutMaxGray, self.cmdStartToSave)
        MainWindow.setTabOrder(self.cmdStartToSave, self.cmbProjects)
        MainWindow.setTabOrder(self.cmbProjects, self.chkRemoveVoluminas)
        MainWindow.setTabOrder(self.chkRemoveVoluminas, self.nutRemoveVoluminas)
        MainWindow.setTabOrder(self.nutRemoveVoluminas, self.chkFillCavities)
        MainWindow.setTabOrder(self.chkFillCavities, self.nutFillCavities)
        MainWindow.setTabOrder(self.nutFillCavities, self.cmdStartEditor)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Folder with DICOM Files:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtDcm.setText(QtGui.QApplication.translate("MainWindow", "multiImageTest/", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDcm.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdStartConvert.setText(QtGui.QApplication.translate("MainWindow", "START", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Convert DCM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Project Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtProject.setText(QtGui.QApplication.translate("MainWindow", "testImage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", ".sav", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdStartToSave.setText(QtGui.QApplication.translate("MainWindow", "START", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Minimum Gray Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Maximum Gray Value", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFlipTop.setText(QtGui.QApplication.translate("MainWindow", "flip Top", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFlipRight.setText(QtGui.QApplication.translate("MainWindow", "flip Right", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Generate Project", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdStartEditor.setText(QtGui.QApplication.translate("MainWindow", "START", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Select Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkRemoveVoluminas.setText(QtGui.QApplication.translate("MainWindow", "Remove Voluminas Smaller Than:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkFillCavities.setText(QtGui.QApplication.translate("MainWindow", "Fill Cavities Smaller than:            ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Start Editor", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

